### ISSUE TITLE
couldnt find ibeacons

### ISSUE THREAD

**Issue by zehradogru** [satyyyaamm/iBeacon-flutter#1]
Hello, I downloaded your code and tried it but it didn't find my ibeacons. I don't understand why. What can I do?

**Comment by satyyyaamm** [comment]
Hey, don’t worry i’ll help you out with that, tell me more about what you
did and what are console log.

Thanks

**Comment by zehradogru** [comment]
Sorry to bother you. I found the problem. I just wrote the uuid number wrong. :(( Your code was reallyyyyy helpful thanks a lot.

**Comment by satyyyaamm** [comment]
Congratulations!
I’m glad that it help, can you please maybe drop a comment on linkedin on
the medium post and clap on medium post, please.

Thanks!
